[pytest]

markers =
    authorization: test to run by authorization feature
    courses: test to run by courses feature
    regression: test to run for regression
    registration: test to run by registration feature